name: Release Actoins Workflow

on:
  release:
    types: [published]

jobs:
  #
  # Demo build steps
  #
  build_stage:
    name: "Demo Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pretend to Build
        run: echo "Pretend to build something here."

      - name: Archive dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: demo-artifact
          path: dist/


  add_assets_to_release:
    name: "Add the Release Assets"
    needs:
      - build_stage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          path: all-artifacts

      - name: Zip Demo Distribution
        run: |
          echo ${{ github.ref_name }} > version
          zip -r ../demo-asset.zip .
        working-directory: ${{steps.download.outputs.download-path}}/demo-artifact

      # API Documentation https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset
      - name: Upload Asset
        run: |
          url=$(echo "${{ github.event.release.upload_url }}?name=demo-dist-${{ github.ref_name }}.zip" | sed -e 's/{[^}]*}//')
          curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          -X POST ${url} \
          --data-binary "@demo-asset.zip"
        working-directory: ${{steps.download.outputs.download-path}}


  ship_it:
    name: "Ship It!"
    needs:
      - build_stage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Pretend to ship it
        run: echo "Pretending to ship it. Bon Voyage!"
